CREATE SCHEMA IF NOT EXISTS MANAGE_DB.FILE_FORMATS;

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.csv_fileformat
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL','null')
  EMPTY_FIELD_AS_NULL = TRUE;
