CREATE SCHEMA IF NOT EXISTS MANAGE_DB.EXTERNAL_STAGES;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.csv_folder
  URL = 's3://snowflake-db-np/snowpipe/'
  STORAGE_INTEGRATION = s3_int
  FILE_FORMAT = MANAGE_DB.FILE_FORMATS.csv_fileformat;


LIST @MANAGE_DB.EXTERNAL_STAGES.csv_folder;
DESC STAGE MANAGE_DB.EXTERNAL_STAGES.csv_folder;