CREATE SCHEMA IF NOT EXISTS MANAGE_DB.PIPES;

CREATE OR REPLACE PIPE MANAGE_DB.PIPES.employee_pipe
  AUTO_INGEST = TRUE
AS
COPY INTO first_db.public.employees
FROM @MANAGE_DB.EXTERNAL_STAGES.csv_folder;

DESC PIPE MANAGE_DB.PIPES.employee_pipe;
SHOW PIPES IN SCHEMA MANAGE_DB.PIPES;